ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'


Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/jammy64"

 config.vm.provision "shell", inline: <<-SHELL
   sudo bash /vagrant/docker-script.sh
 SHELL

 config.vm.define "manager01" do |manager01|
   manager01.vm.network :forwarded_port, guest: 8081, host: 8081
   manager01.vm.network :forwarded_port, guest: 8087, host: 8087
   manager01.vm.network :forwarded_port, guest: 9443, host: 9443
   manager01.vm.hostname = "manager01"
   manager01.vm.network "private_network", ip: "192.168.56.10"
  
   manager01.vm.provider "virtualbox" do |vb|
     vb.name = "manager01"
     vb.memory = "2048"
     vb.cpus = 1
   end


   manager01.vm.provision "shell", inline: <<-SHELL
     sudo bash /vagrant/swarm_init_manager.sh
   SHELL
 end


 config.vm.define "worker01" do |worker01|
   worker01.vm.hostname = "worker01"
   worker01.vm.network "private_network", ip: "192.168.56.11"
  
   worker01.vm.provider "virtualbox" do |vb|
     vb.name = "worker01"
     vb.memory = "2048"
     vb.cpus = 1
   end


   worker01.vm.provision "shell", inline: <<-SHELL
     sudo bash /vagrant/swarm_init_worker.sh
   SHELL
 end


 config.vm.define "worker02" do |worker02|
   worker02.vm.hostname = "worker02"
   worker02.vm.network "private_network", ip: "192.168.56.12"


   worker02.vm.provider "virtualbox" do |vb|
     vb.name = "worker02"
     vb.memory = "2048"
     vb.cpus = 1
   end
   worker02.vm.provision "shell", inline: <<-SHELL
     sudo bash /vagrant/swarm_init_worker.sh
   SHELL
 end
end
